config/routes.rb
Rails.application.routes.draw do

  resources :contacts
  root 'welcome#index'

  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles = Article.all
    end
    def edit
    	@article = Article.find(params[:id])
    end
    def new 
    end
    def create
    	#render plain: params[:article].inspect
    	@article = Article.new(article_params)
    	if @article.save
    		redirect_to @article
    	else
    		render action: 'new'
    	end

    end
    def show
    	@article = Article.find(params[:id])
    end
    def update
    	@article = Article.find(params[:id])
    	if @article.update(article_params)
    		redirect_to @article
    	else
    		render "update"
    	end
    end
    private 
    def article_params
    	params.require(:article).permit(:title, :text)
    end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        UserMailer.new_contact_email(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:firstName, :lastName, :phone, :email, :message)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/_form.html.erb
<%= form_for :article do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label :text %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>
<%= link_to 'Back', articles_path %>

app/views/articles/edit.html.erb
<h1>Updating article "<%= @article.title %>"</h1>
<%= render 'form' %>

app/views/articles/index.html.erb
<h1>Listing articles</h1>
 <%= link_to 'New article', new_article_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th>Actions</th>
  </tr>
 
  <% @articles.each do |article| %>
    <tr>
      <td><%= article.title %></td>
      <td><%= article.text %></td>
      <td><%= link_to "Edit", edit_article_path(article) %></td>
    </tr>
  <% end %>
</table>

app/views/articles/new.html.erb
<h1>New article</h1>
<%= render 'form' %>

app/views/articles/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @article.text %>
</p>
<%= link_to 'Back', controller:articles_path %>

app/views/contacts/_form.html.erb
<%= form_for(@contact) do |f| %>
  <% if @contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% @contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :firstName %><br>
    <%= f.text_field :firstName %>
  </div>
  <div class="field">
    <%= f.label :lastName %><br>
    <%= f.text_field :lastName %>
  </div>
  <div class="field">
    <%= f.label :phone %><br>
    <%= f.text_field :phone %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form' %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Firstname</th>
      <th>Lastname</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Message</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.firstName %></td>
        <td><%= contact.lastName %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.email %></td>
        <td><%= contact.message %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form' %>

<%= link_to 'Back', contacts_path %>

app/views/contacts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Firstname:</strong>
  <%= @contact.firstName %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @contact.lastName %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @contact.phone %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Message:</strong>
  <%= @contact.message %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Group II</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
		<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  	<h1>Welcome to Cantact List Application</h1>
</div>
</nav>
<div class="container">

<!--<%= link_to 'Go to blog >>>', controller: 'articles' %>-->

<%= link_to 'Contact lists >>>', controller: 'contacts' %>
</div>